---
- hosts: test
  remote_user: root
  serial: 2
 
  tasks: 
    - name: Update Ansible Hosts File
      template: src=./cfg/ansible-hosts.txt dest=/etc/ansible/hosts

      
  tasks:
    - name: Node0 - Configure /etc/sysconfig/network-scripts/eth0
      template: src=./cfg/ifcfg-eth0-10.txt dest=/etc/sysconfig/network-scripts/ifcfg-eth0
    - name: Node0 - Configured /etc/network
      template: src=./cfg/hostname-10.txt dest=/etc/sysconfig/network
      when: (ansible_eth0.macaddress == "10:00:00:00:00:10" )   

  tasks: 
    - name: Restart eth0
      service:
        name: NetworkManager
        state: restarted

