---
- hosts: test
  remote_user: root
  serial: 2
  
# Temporarily no DRY - working on Jinga2 Conditional Template

  tasks: 
    - name: Update Ansible Hosts File
      template: src=./cfg/ansible-hosts.txt dest=/etc/ansible/hosts

      
  tasks: 
    - name: Configure /etc/sysconfig/network-scripts/eth0
      template: src=./cfg/ifcfg-eth0-99.txt dest=/etc/sysconfig/network-scripts/ifcfg-eth0
    - name: Configured /etc/network
      template: src=./cfg/hostname-99.txt dest=/etc/sysconfig/network
      when: (ansible_eth0.macaddress == "10:00:00:00:00:99" )
      
