---
- hosts: test
  remote_user: root
  serial: 2
  
# Temporarily no DRY - working on Jinga2 Conditional Template

  macaddress_node_10: '100000000010'
  macaddress_node_11: '100000000011'
  macaddress_node_12: '100000000012'
  macaddress_node_13: '100000000013'
  macaddress_node_14: '100000000014'
  macaddress_node_15: '100000000015'
  macaddress_node_16: '100000000016'
  macaddress_node_04: '100000000004'
  macaddress_node_02: '100000000002'
  macaddress_node_90: '100000000099'
  

  tasks: 
    - name: Update Ansible Hosts File
      template: src=./cfg/ansible-hosts.txt dest=/etc/ansible/hosts

      
  tasks: 
    - name: Base - Configure /etc/sysconfig/network-scripts/eth0
      template: src=./cfg/ifcfg-eth0-99.txt dest=/etc/sysconfig/network-scripts/ifcfg-eth0
    - name: Configured /etc/network
      template: src=./cfg/hostname-99.txt dest=/etc/sysconfig/network
      when: (ansible_eth0.macaddress == "10:00:00:00:00:99" )
      